# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for NVIDIA ARM64 platform-specific drivers
#

obj-$(CONFIG_MTK_PCIE_HOTPLUG) += mtk-pcie-hotplug.o
obj-$(CONFIG_MTK_PCIE_HOTPLUG) += mtk-pcie-mmio-resources.o

